version: "3.7"

services:

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  auth:
    image: alxgrk/redis-hackathon-auth-service:latest
    ports:
      - 8081:8081
    env_file:
      - ./auth-service/.env

  bidding:
    image: alxgrk/redis-hackathon-bidding-service:latest
    ports:
      - 8082:8082
    env_file:
      - ./bidding-service/.env

  auctioning:
    image: alxgrk/redis-hackathon-auctioning-service:latest
    ports:
      - 8083:8083
    env_file:
      - ./auctioning-service/.env

volumes:
  redis-data:
